# Generated by Django 2.2.2 on 2020-07-16 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='engine',
            field=models.CharField(choices=[('telegram', 'telegram')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userlink',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Bot'),
        ),
        migrations.AlterField(
            model_name='userlink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
