# Generated by Django 2.2.2 on 2020-07-16 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20200717_0038'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userlink',
            unique_together={('bot', 'chat_id')},
        ),
    ]
