default_app_config = 'telebot.apps.LoggerConfig'

LOG_LEVEL_NONE = 0
LOG_LEVEL_ALL = 1
LOG_LEVEL_ERRORS = 2

AVAILABLE_LOG_LEVELS = [LOG_LEVEL_NONE, LOG_LEVEL_ALL, LOG_LEVEL_ERRORS]

FROM_BOT = 0
FROM_USER = 1
