# Generated by Django 2.2.2 on 2020-07-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelogrecord',
            name='error',
            field=models.TextField(null=True),
        ),
    ]
